version: "3.9"
services:
  product-container:
    container_name: product-ecomm
    build: ./product/
    ports:
      - 3001:3001
    volumes:
      - ./:/app-product
    environment:
      - PORT=3001
      - DB_HOST=mongo-database
    depends_on:
      - mongo-database
  account-container:
    container_name: account-ecomm
    build: ./account/
    ports:
      - 3002:3002
    volumes:
      - ./:/app-account
    environment:
      - PORT=3002
      - DB_HOST=mongo-database
    depends_on:
      - mongo-database
  mongo-database:
    container_name: 'mongo-ecomm'
    image: mongo:5
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongo-ecomm-volume:/var/lib/mysql
  mysql-database:
    container_name: 'mysql-ecomm'
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql-ecomm-volume:/var/lib/mysql
volumes:
  mysql-ecomm-volume:
  mongo-ecomm-volume: